<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>eda551dd-1266-4982-9a34-30d1974fdb09</UserSecretsId>
    <SpaRoot>..\CrmApp.Client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:4200</SpaProxyServerUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner.SqlServer" Version="7.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>8.*</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrmApp.Domain\CrmApp.Domain.csproj" />
    <ProjectReference Include="..\CrmApp.Infrastructure\CrmApp.Infrastructure.csproj" />
    <ProjectReference Include="..\CrmApp.Migrations\CrmApp.Migrations.csproj" />
  </ItemGroup>

</Project>
