/**
 * Registered icon names (used as `svgIcon="..."` and stored by the icon picker) mapped to
 * Lucide icon files (node_modules/lucide-static/icons, copied to assets/lucide at build time).
 * Keep the keys stable — only change the Lucide file names on the right.
 */
export const LUCIDE_ICONS: Record<string, string> = {
  // App / navigation
  network_intel_node: 'network',
  account_circle: 'circle-user-round',
  logout: 'log-out',
  back: 'arrow-left',
  website: 'globe',
  chevron_right: 'chevron-right',
  keyboard_arrow_up: 'chevron-up',
  keyboard_arrow_down: 'chevron-down',
  expand_more: 'chevron-down',
  arrow_right: 'arrow-right',
  arrow_menu_close: 'panel-left-close',
  arrow_menu_open: 'panel-left-open',
  open_in_full: 'maximize-2',
  open_in_new: 'external-link',
  drag_indicator: 'grip-vertical',
  sync_alt: 'arrow-left-right',
  settings: 'settings',
  productivity: 'gauge',
  business_center: 'briefcase-business',
  view_kanban: 'square-kanban',
  view_column: 'columns-3',
  table_edit: 'table-properties',
  strategy: 'target',
  automation: 'workflow',
  finance_mode: 'chart-line',
  shopping_cart: 'shopping-cart',
  inventory_2: 'package',
  book: 'book-open',
  category: 'shapes',
  tag: 'tag',
  list: 'list',

  // Actions
  add: 'plus',
  add_circle: 'circle-plus',
  add_task: 'clipboard-plus',
  delete: 'trash-2',
  edit: 'pencil',
  save: 'save',
  send: 'send',
  sort: 'arrow-down-wide-narrow',
  undo: 'undo-2',
  retry: 'refresh-cw',
  autorenew: 'refresh-cw',
  content_copy: 'copy',
  upload: 'upload',
  download: 'download',
  search: 'search',
  search_off: 'search-x',
  filter_alt: 'funnel',
  filter_alt_off: 'funnel-x',
  close: 'x',
  close_bold: 'x',
  cancel: 'circle-x',
  hide: 'eye-off',
  visibility: 'eye',
  visibility_off: 'eye-off',
  pin: 'pin',
  pin_off: 'pin-off',
  insert_text: 'text-cursor-input',
  text_fields: 'type',
  calculate: 'calculator',
  chat_paste_go: 'message-square-share',
  frame_inspect: 'scan-search',
  palette: 'palette',

  // Status
  success: 'circle-check',
  check_circle: 'circle-check',
  error: 'circle-x',
  warning: 'circle-alert',
  info: 'info',
  question: 'circle-question-mark',
  help: 'circle-question-mark',
  pending: 'circle-ellipsis',
  pause_circle: 'circle-pause',
  check_box: 'square-check',
  check_box_blank: 'square',
  radio_button_checked: 'circle-dot',
  radio_button_unchecked: 'circle',
  toggle_on: 'toggle-right',
  all_inclusive: 'infinity',
  cloud_sync: 'cloud',

  // Time
  timer: 'timer',
  history: 'history',
  schedule: 'clock',
  today: 'calendar-days',
  calendar_today: 'calendar',
  calendar_month: 'calendar-days',
  hourglass_top: 'hourglass',
  hourglass_empty: 'hourglass',

  // People / security
  person: 'user',
  person_card: 'contact-round',
  person_search: 'user-search',
  person_shield: 'shield-user',
  admin_panel: 'user-cog',
  account_active: 'user-check',
  account_off: 'user-x',
  contact_mail: 'contact',
  mail_outline: 'mail',
  phone_outlined: 'phone',
  work_outline: 'briefcase',
  add_business: 'store',
  handshake: 'handshake',
  shield: 'shield',
  shield_lock: 'shield-ellipsis',
  shield_question: 'shield-question-mark',
  encrypted_add: 'shield-plus',
  lock_reset: 'rotate-ccw-key',
  key_vertical: 'key-round',

  // Files / documents
  folder: 'folder',
  folder_check: 'folder-check',
  folder_data: 'folder-cog',
  folder_shared: 'folder-symlink',
  note_stack: 'files',
  note_stack_add: 'file-plus',
  contract: 'file-signature',
  description: 'file-text',
  task: 'clipboard-check',

  // Media
  mic: 'mic',
  adaptive_audio_mic: 'audio-lines',
  interpreter_mode: 'languages',

  // Theme (kept for icon picker compatibility)
  dark_mode: 'moon',
  light_mode: 'sun',
  system_mode: 'sun-moon',
};
